#!/usr/bin/env bash
# Packages both charts into a single k3s HelmChart CRD manifest — the
# "cluster rebuilds itself from one file" path docs/05 describes, as a
# second, separate install path alongside the `helm install`/`helm upgrade`
# commands already used and documented (not a replacement for them).
#
# `chartContent` (base64 of `helm package`'s .tgz output) is the mechanism
# here, not a `repo:` reference — neither chart is published anywhere, and
# there's no host path into the k3s server pod under k3d without recreating
# the cluster with an extra --volume, which this script doesn't require.
#
# Usage:
#   k3s/bootstrap/package.sh > k3s/bootstrap/helmcharts.yaml
#   docker cp k3s/bootstrap/helmcharts.yaml \
#     k3d-<cluster>-server-0:/var/lib/rancher/k3s/server/manifests/postmortem-helmcharts.yaml
#
# k3s's built-in controller watches that directory continuously, even after
# the node has already booted — no cluster recreation needed to pick it up.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
work_dir="$(mktemp -d)"
trap 'rm -rf "${work_dir}"' EXIT

helm package "${repo_root}/k3s/helm/postmortem-autopilot" --destination "${work_dir}" >&2
helm package "${repo_root}/k3s/helm/postmortem-observability" --destination "${work_dir}" >&2

pipeline_tgz="$(find "${work_dir}" -name 'postmortem-autopilot-*.tgz')"
observability_tgz="$(find "${work_dir}" -name 'postmortem-observability-*.tgz')"

pipeline_b64="$(base64 -w0 "${pipeline_tgz}")"
observability_b64="$(base64 -w0 "${observability_tgz}")"

cat <<YAML
# Generated by k3s/bootstrap/package.sh — do not hand-edit; re-run the
# script instead. Values here mirror values-dev.yaml (k3d image import,
# not a registry pull) since this bootstrap path targets the same dev
# cluster; --set-file-populated prompts aren't available through
# chartContent installs, so prompts default to the image-baked copies.
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: postmortem-autopilot
  namespace: kube-system
spec:
  targetNamespace: postmortem
  chartContent: ${pipeline_b64}
  valuesContent: |-
    pipeline:
      image:
        pullPolicy: Never
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: postmortem-observability
  namespace: kube-system
spec:
  targetNamespace: observability
  chartContent: ${observability_b64}
YAML
